const quotes = [
	'Allein ist besser als mit Schlechten im Verein: mit Guten im Verein, ist besser als allein.',
	'Aller guten Dinge sind drei.',
	'Alles ist seinen Preis wert.',
	'Alles zu seiner Zeit.',
	'Alte Füchse gehen schwer in die Falle.',
	'Alte soll man ehren, Junge soll man lehren.',
	'Am vielen Lachen erkennt man den Narren.',
	'An den Früchten erkennt man den Baum.',
	'Andere Länder, andere Sitten.',
	'Anfangen ist leicht, beharren eine Kunst.',
	'Arzt, hilf dir selber!',
	'Außerordentliche Übel erfordern außerordentliche Mittel.',
	'Auch der kleinste Feind ist nicht zu verachten.',
	'Auf einen großen Klotz gehört ein großer Keil.',
	'Aus den Augen, aus dem Sinn.',
	'Aus einem Stein ist schwer Öl pressen.',
	'Aus Schaden wird man klug.',
	'Aufgewärmter Kohl war niemals gut.',
	'Aufschub bringt Gefahr.',
	'Aus einer Mücke einen Elefanten machen.',
	'Bald geben, ist doppelt geben.',
	'Bald reif hält nicht steif.',
	'Bedenke das Ende.',
	'Bedenke, dass du sterben musst.',
	'Behüte mich Gott vor meinen Freunden, mit den Feinden will ich schon fertig werden.',
	'Bei offener Kiste mag auch der Fromme ein Schalk werden.',
	'Berühre nicht alte Wunden.',
	'Besser allein als in schlechter Gesellschaft.',
	'Besser arm in Ehren als reich in Schanden',
	'Besser spät als nie.',
	'Beispiele tun oft mehr als viel Wort\' und Lehr\'.',
	'Besser ein Narr mit allen andern, als ein Weiser und allein.',
	'Beiß nicht in die Hand, die dich füttert.',
	'Bellende Hunde beißen nicht.',
	'Besser ein Spatz in der Hand, als eine Taube auf dem Dach.',
	'Blinder Eifer ist Feuer ohne Licht.',
	'Blut ist dicker als Wasser',
	'Blödes Herz buhlt keine schöne Frau.',
	'Böses mit Gutem vergelten.',
	'Das Auge sieht weit, der Verstand noch weiter.',
	'Das beste Kommt selten hernach.',
	'Das Billige ist immer das Teuerste.',
	'Das böse Gewissen verrät sich selbst.',
	'Das Eisen schmieden, solange es heiß ist.',
	'Das Glück hilft dem Kühnen.',
	'Das Herz luegt nicht.',
	'Das Kind mit dem Bade ausschütten.',
	'Das Pferd stirbt oft, ehe das Gras wächst.',
	'Das Weib ist des Mannes größtes Glück oder Unglück.',
	'Das Word verhallt, die Schrift bleibt.',
	'Deine Wäsche wasche zu Hause.',
	'Der Fisch stinkt vom Kopf her.',
	'Der Geizige ist keinem gut, ihm selbst der Ärgste.',
	'Der Gesunde weiß nicht, wie reich er ist.',
	'Der Stärkere hat immer Recht.',
	'Der Ton macht die Musik.',
	'Die Arznei ist oft ärger als das Übel.',
	'Die besten Schwimmer ertrinken.',
	'Die beste Verteidigung ist der Angriff.',
	'Die besten Gedanken kommen allzeit hinterdrein.',
	'Die Ochsen hinter dem Wagen spannen.',
	'Dem Trinker kommt der Durst.',
	'Der Apfel fällt nicht weit vom Stamm.',
	'Der Ertrinkende greift nach einem Strohhalm.',
	'Der Horcher an der Wand hört seine eigene Schand.',
	'Der Hund bellt und die Karawane geht vorüber.',
	'Der liebe Gott ist immer mit den stärksten Bataillonen.',
	'Der gerade Weg ist der beste.',
	'Der Schuster hat die schlechtesten Schuhe.',
	'Der Weg zur Hölle ist mit guten Vorsätzen gepflastert.',
	'Der muss einen langen Löffel haben, der mit dem Teufel essen will.',
	'Der Mensch denkt, Gott lenkt.',
	'Der Schein trügt.',
	'Des Menschen Wille ist sein Himmelreich.',
	'Doppelt genählt hält besser.',
	'Du siehst den Wald vor lauter Bäumen nicht.',
	'Den Teufel nicht an die Wand malen.',
	'Der Eider dünket seine Ente ein Falk.',
	'Die Ersten werden die Letzten sein.',
	'Die großen Fische fressen die kleinen.',
	'Die Ratten verlassen das sinkende Schiff.',
	'Draußen hat man hundert Augen, daheim kaum eins.',
	'Durch Völlerei kommen mehr um denn durchs Schwert',
	'Das Kind ins Wasser gefallen.',
	'Ehrlich währt am längsten.',
	'Eigenlob stinkt.',
	'Ein Feind ist zuviel, und hundert Freunde nicht genug.',
	'Ein gewiß[sic, Gewiss] ist better als zehn Unghewiß[sic, Ungewiss].',
	'Ein Heute ist besser denn zehn Morgen.',
	'Ein kiel trebt den andere aus.',
	'Ende gut, alles gut.',
	'Erst denken, dann lenken.',
	'Erst denken, dann handeln',
	'Ein jeder habe das fröhliche, gesunde Mißtrauen.',
	'Ein Scheit allein brennt nicht.',
	'Einer allein ist nicht einmal gut im Paradies.',
	'Er war in Rom und hat den Papst nicht gesehen.',
	'Es ist keiner so blind, wie der, der nicht sehen will.',
	'Es ist nicht alles Gold, was glänzt.',
	'Ein Unglück kommt selten allein.',
	'Eile mit Weile.',
	'Eine Schwalbe macht noch keinen Sommer!',
	'Eulen nach Athen tragen',
	'Erst wägen, dann wagen.',
	'Es ist übel, Hasen mit Trommeln fangen.',
	'Faulheit ist der Schlüssel zur Armut.',
	'Galle im Herzen, Honig im Mund',
	'Gelernt ist gelernt.',
	'Gebranntes Kind scheut das Feuer.',
	'Geklagtes Leid ist halbes Leid.',
	'Geld macht nicht glücklich.',
	'Gemein Gerücht ist selten erlogen.',
	'Geschenk vom Feind ist nicht gut gemeint.',
	'Geschichte wiederholt sich.',
	'Gesunder Mann, reicher Mann.',
	'Geteilte Freude ist doppelte Freude, geteilter Schmerz ist halber Schmerz.',
	'Gleiche Gemüter suchen sich.',
	'Gleiches muß durch Gleiches geheilt werden.',
	'Gleich sucht sich, Gleich findet sich.',
	'Glück bringt Neider.',
	'Golden Gebiss macht das Pferd besser.',
	'Gott bewahre mich vor jemand, der nur ein Büchlein gelesen hat.',
	'Gott lässt uns wohl sinken, Aber nicht ertrinken.',
	'Gut verloren, etwas verloren; Ehre verloren, viel verloren; Mut verloren, alles verloren.',
	'Guter Willen gilt für die Tat.',
	'Halt\'s Maul, so fliegt dir keine Mücke hinein.',
	'Heute mir, morgen dir.',
	'Hochmut kommt vor dem Fall.',
	'Hoffen und harren macht manchen zum Narren.',
	'Hurtig zum Imbiß, hurtig zur Arbeit.',
	'Hütet euch vor den falschen Propheten.',
	'In der Furt soll man die Pferde nicht wechseln.',
	'In eigener Sache kann niemand Richter sein.',
	'Im Becher ersaufen mehr als im Meer.',
	'Im Hause des Gehenkten rede nicht vom Stricke.',
	'Im Glück nicht jubeln, im Sturm nicht zagen.',
	'Im scherz klopft man oft, und im Ernst wird auf.',
	'In Zweifelsfalle draußen bleiben',
	'Je mehr man die Katze streichelt, desto höher trägt sie den Schwanz.',
	'Je näher dem Bein, desto süßer das Fleisch.',
	'Je toller, desto besser.',
	'Jedem gefällt das Seine.',
	'Jedem Narren gefällt seine Kappe.',
	'Jedes Warum hat seinen Darum.',
	'Jung getollt, alt gezollt.',
	'Kehre vor Deiner eigenen Tür.',
	'Keiner weiss wo dem Andern der Schuh drückt.',
	'Kein Buch so schlecht, es steckt was Guten drin.',
	'Keing Ding ist so gering, es ist einer Bitte werth.',
	'Kleine Kessel haben große Ohren.',
	'Krummes Holz gibt auch gerades Feuer.',
	'Sich nicht um ungelegte Eier kümmern.',
	'Laufen ist eine Schande, aber gesund.',
	'Lebe wie du kannst, nicht wie du willst.',
	'Leere Ähren stehen aufrecht.',
	'Leichter gesagt als getan.',
	'Leicht versprochen, leicht gebrochen.',
	'Leid oder Freud\', in fünfzig Jahren ist\'s alles eins.',
	'Lieben und Husten lassen sich nicht verbergen.',
	'Lieber biegen, als brechen.',
	'Lieber ein Ende mit Schmerzen als Schmerzen ohne Ende.',
	'Lieber ein Ende mit Schrecken als ein Schrecken ohne Ende.',
	'Lügen haben kurze Beine.',
	'Lösche nicht, wo dich\'s nicht brennt.',
	'Man findet bald einen Stecken, wenn man einen Hund schlagen will.',
	'Man kann die Natur nicht ändern.',
	'Man muß die Dinge nehmnen, wie sie kommen.',
	'Man muss das Eisen schmieden solange es heiß ist.',
	'Man sieht das Hirn nicht an der Stirn.',
	'Man sieht am Ende wohl, Wie man es loben soll.',
	'Man sollte das Fell des Bären nicht verkaufen, bevor man ihn erlegt hat.',
	'Man soll den Tag nicht vor dem Abend loben.',
	'Man soll kein Öl ins Feuer giessen.',
	'Man wirft keine Perlen vor die Säue.',
	'Mancher küßt die Hand, die er abbhauen möchte.',
	'Mit dem, som man ausgibt, mit demselben wird es ausgemessen.',
	'Mit den Ohren such\' dir eine Frau, zieh\' mehr die Ohren als die Augen zu Rate.',
	'Mit Honig fängt man Fliegen.',
	'Mitgefangen, mitgehangen.',
	'Morgenstund hat Gold im Mund.',
	'Narren bedürfen der Schellen nicht.',
	'Natur geht vor Lehre.',
	'Neidhard ist gestorben, hat aber viele Kinder hinterlassen.',
	'Neue Besen kehren gut.',
	'Nicht alle sind Diebe die der Hund anbellt.',
	'Niemand ist unersetzlich.',
	'Niemand kann sich über das Meer beklagen, der zum zweiten Male Schiffbruch erlitten hat.',
	'Nur tote Fische schwimmen mit dem Strom.',
	'Öl in Feuer schütten.',
	'Quatsch keine Opern.',
	'Raten ist nicht zwingen.',
	'Rund is die Welt, drum Brüder laßt uns reisen.',
	'Schande dem, der schlecht davon denkt.',
	'Schlimme Sitten, gut Gesetz.',
	'Schmieds Pferd und Schusters Weiber gehen meistens barfuss.',
	'Schnell Urteil hat Reue feil.',
	'Schälke muss man mit Schälken fangen.',
	'Schön ist, was schön lässt.',
	'Selbst dem Teufel sein Recht geben.',
	'Sicher ist sicher.',
	'Steter Tropfen höhlt den Stein.',
	'Schuster, bleib bei deinen Leisten.',
	'Man sieht das Hirn nicht an der Stirn.',
	'Schlafende Hunde soll man nicht wecken.',
	'Selbst ist der Mann.',
	'Sieht doch wohl die Katze den Kaiser an.',
	'Sorge macht vor Zeiten grau.',
	'Spiele nicht mit Feuer.',
	'Stehend Wasser wird stinkend.',
	'Taten statt Worte!',
	'Taten sagen mehr als Wörter.',
	'Lass Wörtern Taten folgen!',
	'Lass Taten sprechen!',
	'Teile und herrsche!',
	'Tut nach meinen Worten und nicht mach meinen Werken.',
	'Übung macht den Meister.',
	'Unter den Blinden ist der Einäugige König.',
	'Unter dem blṻhenden Strauch liegt oft ein giftige Schlange versteckt.',
	'Verborgener Schatz ist nichts wert.',
	'Verbotene Frucht schmeckt am besten.',
	'Von großen Blöcken haut man große Stücke.',
	'Verstand kommt mit den Jahren.',
	'Vertrauen erweckt Vertrauen.',
	'Viel stroh, wenig Korn.',
	'Viel Wissen macht Kopfweh.',
	'Vom Regen in die Traufe.',
	'Vorbeugen ist besser als heilen.',
	'Vorrath nimmer schadet.',
	'Wahrheit gibt kurzen Bescheid, Luege macht viel Redens.',
	'Was du allein wissen willst, das sage niemand.',
	'Was Gutes kommt wieder.',
	'Wem das Ferkel geboten wird, soll den Sack bereit haben.',
	'Wem der Rock paßt, mag ihn anziehen.',
	'Wem nicht zu raten ist, dem ist auch nicht zu helfen.',
	'Wenn alle dir sagen, du seiest betrunken, geh\' schlafen.',
	'Wenn das Haupt krank ist, trauern alle Glieder.',
	'Wenn der Berg nicht zum Propheten kommt, muß der Prophet zum Berge gehen.',
	'Wenn der Himmel einfällt bleibt nirgend ein stehen.',
	'Wenn du dich nicht selber kitzelst, ein and\'rer wird nicht für dich lachen.',
	'Wem Gott gibt ein Amt, dem gibt er auch Verstand.',
	'Wenn ein Freund bittet, so gilt nicht morgen.',
	'Wenn jeder Herr ist, wer bringt aus dem Stalle den Mist?',
	'Wenn strafen will die Gotteshand, so nimmt sie einem den Verstand.',
	'Wer auf Gott vertraut, hat gut gebaut.',
	'Wer befehlen will, muß gehorchen lernen.',
	'Wer den Acker nicht will graben, der wird nicht als Unkraut haben.',
	'Wer den Kern essen will, muss die Nuss knacken.',
	'Wer durch Fliehen sich mag retten, kann wieder vor die Luke treten.',
	'Wer Eier unter den Füßen hat, muss leise auftreten.',
	'Wer ein Kalb stiehlt, stiehlt eine Kuh.',
	'Wer einen grossen Sprung thun will, geht vorher zuruck.',
	'Wer Feuer bedarf, sucht es in der Asche.',
	'Wer Honig lecken will, darf die Bienen nicht scheuen.',
	'Wer keine Neider hat, hat auch klein Glück.',
	'Wer mich liebt, der libt auch meinen Hund.',
	'Wer nicht mit mir ist, der ist wider mich.',
	'Wer nicht vorwärts kommt, kommt rückwärts.',
	'Wer sich unter die Kleie mischt, den fressen die Schweine.',
	'Wer Vögel fangen will, muß nicht mit Knutteln dreinwerfen.',
	'Wer zuerst kommt, mahlt zuerst.',
	'Wer zuletzt lacht, lacht am besten.',
	'Wer zwei Hasen auf einmal jagt bekommt keinen.',
	'Wer\'s allen recht machen will muss früh aufstehen.',
	'Wie du dein Bett macht, so magst Du darauf schlafen.',
	'Wiederholung ist die Mutter der Weisheit.',
	'Wie der Vater, so der Sohn.',
	'Wie die Mutter, so die Tochter.',
	'Wie man in den Wald hineinruft, so schallt es heraus.',
	'Was nicht ist, kann noch werden.',
	'Wenn das Wörtchen',
	'nicht wär, wär mein Vater Millionär.',
	'Wer nicht hören will, muss fühlen.',
	'Wie der Lohn, so die Arbeit.',
	'Wie die Alten singen, so zwitschern auch die Jungen.',
	'Wie man in den Wald hineinruft, so schallt es zurück.',
	'Wissen ist Macht.',
	'Wer nicht wagt, der nicht gewinnt.',
	'Wer anderen eine Grube gräbt, fällt selbst hinein.',
	'Wer A sagt, muss auch B sagen. (Plattdeutsche Variante: De A seggt, mut ok B seggen)',
	'Wenn der Reiter nichts taugt, ist das Pferd schuld.',
	'Wo der Zaun am niedrigsten is, springt jeder über.',
	'Wo Rauch ist, da ist auch Feuer.',
	'Wo der liebe Gott eine Kirche baut, da baut der Teufel eine Kapelle daneben.',
	'Wo keine Versuchung, da ist kein Ehre.',
	'Worte sind gut, wenn Werke folgen.',
	'Wächst die Ehre spannenlang wächst die Thorheit ellenlang.',
	'Wähle von zwei Übeln das Kleinste.',
	'Wärme bringt Leben, Kälte Tod',
	'Zeit ist das teuerste Kleinod.',
	'Zu nacht sind alle Katzen grau.',
	'Zum Dichter muß man geboren sein, Redner kann man werden.',
	'Zur rechten Zeit ein Nadelsstich erspart sicherlich neun.'
]

document.getElementById('q').innerText = quotes[Math.floor(Math.random() * quotes.length)]
